### PR TITLE
fix(engines): Revert engine back to 16

### LINKED ISSUE #431: [BUG]: last commit was detected as a fix instead of breaking change (node version)
### What happened?

the package isn't supporting node >= 16 so I can't install my project. This is because of BREAKING CHANGE of [this commit](https://github.com/octokit/plugin-retry.js/commit/52cf451c23b82898046f861b5806915e93561f98) wasn't detected

### Versions

@octokit/plugin-retry@4.1.4

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by benmvp**
#430 upgraded the Node version to 18, but as a fix released in [`4.1.4`](https://www.npmjs.com/package/@octokit/plugin-retry/v/4.1.4) (instead of as a breaking change). So it breaks consumers of the library (such as [`semantic-release`](https://github.com/semantic-release/semantic-release)) that are still on Node 16.

Resolves #431

----

### Before the change?

* Able to install a package using `@ocktokit/plugin-retry` with Node 16.

### After the change?

* Unable to install a package using `@ocktokit/plugin-retry` with Node 16 because it requires Node 18.

### Other information

n/a

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?
It doesn't. The previous PR did

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [ ] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by wolfy1339** [comment]
Can you also update the build script: `scripts/build.mjs` to use node 16

**Comment by benmvp** [comment]
> Can you also update the build script: `scripts/build.mjs` to use node 16

done and done!

**Review by wolfy1339 — APPROVED** [review]

**Comment by benmvp** [comment]
Thanks for being so responsive @wolfy1339! 🎉  Such a quick turnaround 🙏🏾

**Comment by benmvp** [comment]
Verified that [`4.1.5`](https://www.npmjs.com/package/@octokit/plugin-retry/v/4.1.5) fixes things!

**Pull request merged**
